/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AchievementHelpPanel: typeof import('./src/components/AchievementHelpPanel.vue')['default']
    Alerts: typeof import('./src/components/Alerts.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AssociateSideNavigation: typeof import('./src/components/AssociateSideNavigation.vue')['default']
    AssociateViewForm: typeof import('./src/components/AssociateViewForm.vue')['default']
    AssociateViewTable: typeof import('./src/components/AssociateViewTable.vue')['default']
    ChallengeHelpPanel: typeof import('./src/components/ChallengeHelpPanel.vue')['default']
    Chat: typeof import('./src/components/Chat.vue')['default']
    ChatHeader: typeof import('./src/components/ChatHeader.vue')['default']
    ChatInputCustomerTextBox: typeof import('./src/components/ChatInputCustomerTextBox.vue')['default']
    ChatInputForm: typeof import('./src/components/ChatInputForm.vue')['default']
    ChatInputSubmissionTextBox: typeof import('./src/components/ChatInputSubmissionTextBox.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ChatStepper: typeof import('./src/components/ChatStepper.vue')['default']
    CombinedSubmissionsDialog: typeof import('./src/components/CombinedSubmissionsDialog.vue')['default']
    CopyTextIcon: typeof import('./src/components/CopyTextIcon.vue')['default']
    HelpPanel: typeof import('./src/components/HelpPanel.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    ManagerSideNavigation: typeof import('./src/components/ManagerSideNavigation.vue')['default']
    ManagerViewForm: typeof import('./src/components/ManagerViewForm.vue')['default']
    ManagerViewTable: typeof import('./src/components/ManagerViewTable.vue')['default']
    MenuButton: typeof import('./src/components/MenuButton.vue')['default']
    Recommendations: typeof import('./src/components/Recommendations.vue')['default']
    RephraseDiff: typeof import('./src/components/RephraseDiff.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNavigation: typeof import('./src/components/SideNavigation.vue')['default']
    ValidationStatus: typeof import('./src/components/ValidationStatus.vue')['default']
  }
}
